name: Test Python Pull Request to main

on:
  pull_request:
    branches: ["main"]

jobs:

  # Test python code
  test:
    runs-on: ubuntu-latest

    steps:
      
      # Checksout repo into github running env 
      - uses: actions/checkout@v3

      # Setups up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Test with pytest
        run: pytest